version: '3.8'


services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=db_postgres_lab1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=0.0.0.0
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 2s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - prologs:/logs
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  prologs:
