version: "3.9"

services:
  app:
    build: .
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - prologs:/logs

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

volumes:
  prologs: