version: '3.8'


services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/db_postgres_lab2 -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./src/flyway/sql:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=db_postgres_lab2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_SERVER=0.0.0.0
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 2s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - prologs:/logs
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  prologs:
